name: mastodon-cross-post CI

on:
  pull_request:
  push:
  schedule:
    # Once every 3 hours.
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v3

      - name: Checkout
        uses: actions/checkout@v3

      - name: "Go: Build"
        run: go build ./...

      - name: "Go: Test"
        run: go test ./...

      - name: "Check: Gofmt"
        run: scripts/check_gofmt.sh

      - name: Fetch latest qself data/
        run: curl --compressed --output data/twitter.toml https://raw.githubusercontent.com/brandur/qself-brandur/master/data/twitter.toml

      - name: "Sync"
        run: ./mastodon-cross-post data/twitter.toml
        env:
          DRY_RUN: false
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          MASTODON_SERVER_URL: "https://mastodon.social"
          MAX_TWEETS_TO_SYNC: 1
          MIN_TWEET_ID: 1345427415061827584
        if: github.ref == 'refs/heads/master'
